/**
 * GitHub REST client for publishing generated projects (docs/ARCHITECTURE.md §7).
 *
 * Thin, typed wrappers around api.github.com using the real Git Data API — every
 * response value (repo URL, default branch, commit sha) comes from GitHub, never
 * from us. Configuration is read from `GITHUB_TOKEN` (required) plus optional
 * `FLEET_GITHUB_OWNER`, `FLEET_GITHUB_REPO_PREFIX` and `FLEET_GITHUB_PRIVATE`.
 */

const API = "https://api.github.com";
const MAX_ATTEMPTS = 3;

/** Retries transient failures (network errors, 429, 5xx) with backoff. */
async function fetchWithRetry(url: string, init: RequestInit): Promise<Response> {
  let attempts = 0;
  for (;;) {
    attempts += 1;
    try {
      const res = await fetch(url, init);
      if (res.status !== 429 && res.status < 500) return res;
      if (attempts >= MAX_ATTEMPTS) return res;
    } catch (error) {
      if (attempts >= MAX_ATTEMPTS) throw error;
    }
    await new Promise((resolve) => setTimeout(resolve, 500 * attempts));
  }
}

export class GitHubError extends Error {
  constructor(
    message: string,
    public status: number = 0,
    public code: string = "GITHUB_API_ERROR"
  ) {
    super(message);
    this.name = "GitHubError";
  }
}

export interface GitHubRepo {
  fullName: string;
  htmlUrl: string;
  defaultBranch: string;
  private: boolean;
}

export interface GitHubConfig {
  token: string | null;
  owner: string | null;
  repoPrefix: string;
  privateRepo: boolean;
}

export function githubConfig(): GitHubConfig {
  return {
    token: process.env.GITHUB_TOKEN?.trim() || null,
    owner: process.env.FLEET_GITHUB_OWNER?.trim() || null,
    repoPrefix: process.env.FLEET_GITHUB_REPO_PREFIX?.trim() || "fleet-app",
    privateRepo: (process.env.FLEET_GITHUB_PRIVATE ?? "true").trim() !== "false",
  };
}

async function request(
  token: string,
  method: string,
  path: string,
  body?: unknown
): Promise<{ status: number; body: unknown }> {
  const res = await fetchWithRetry(`${API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(body !== undefined ? { "content-type": "application/json" } : {}),
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = text;
  }
  return { status: res.status, body: parsed };
}

export async function getAuthenticatedUser(token: string): Promise<string> {
  const { status, body } = await request(token, "GET", "/user");
  if (status !== 200) {
    throw new GitHubError(
      `Could not authenticate with GitHub (${status}) — check GITHUB_TOKEN.`,
      status,
      "GITHUB_AUTH_FAILED"
    );
  }
  const login = (body as { login?: unknown })?.login;
  if (typeof login !== "string" || !login) {
    throw new GitHubError("GitHub returned no user login.", status, "GITHUB_AUTH_FAILED");
  }
  return login;
}

export async function getRepository(
  token: string,
  owner: string,
  repo: string
): Promise<GitHubRepo | null> {
  const { status, body } = await request(token, "GET", `/repos/${owner}/${repo}`);
  if (status === 404) return null;
  if (status !== 200) {
    throw new GitHubError(
      `Failed to look up ${owner}/${repo} (${status}).`,
      status
    );
  }
  const data = body as {
    full_name?: unknown;
    html_url?: unknown;
    default_branch?: unknown;
    private?: unknown;
  };
  return {
    fullName: String(data.full_name ?? `${owner}/${repo}`),
    htmlUrl: String(data.html_url ?? `https://github.com/${owner}/${repo}`),
    defaultBranch: String(data.default_branch ?? "main"),
    private: Boolean(data.private),
  };
}

export async function createRepository(
  token: string,
  owner: string,
  repo: string,
  privateRepo: boolean
): Promise<GitHubRepo> {
  const { status, body } = await request(token, "POST", "/user/repos", {
    name: repo,
    private: privateRepo,
    description: "Generated by Fleet from an approved blueprint.",
    auto_init: false,
  });
  const data = body as {
    full_name?: unknown;
    html_url?: unknown;
    default_branch?: unknown;
  };
  if (status !== 201) {
    const message = (body as { message?: unknown })?.message;
    throw new GitHubError(
      `Could not create ${owner}/${repo} (${status})${typeof message === "string" ? ` — ${message}` : ""}.`,
      status,
      "REPO_CREATE_FAILED"
    );
  }
  return {
    fullName: String(data.full_name ?? `${owner}/${repo}`),
    htmlUrl: String(data.html_url ?? `https://github.com/${owner}/${repo}`),
    defaultBranch: String(data.default_branch ?? "main"),
    private: privateRepo,
  };
}

export async function defaultBranchSha(
  token: string,
  owner: string,
  repo: string,
  branch: string
): Promise<string | null> {
  const { status, body } = await request(
    token,
    "GET",
    `/repos/${owner}/${repo}/git/refs/heads/${branch}`
  );
  if (status !== 200) return null;
  const { object } = body as { object?: { sha?: unknown } };
  return typeof object?.sha === "string" ? object.sha : null;
}

/**
 * Seeds a brand-new (empty) repository with a real `.gitignore` via the
 * Contents API, because GitHub rejects Git Data API blob/commit writes
 * against a repository that has no commits yet (409 "Git Repository is
 * empty."). GitHub returns the seed commit sha, which the Git Data API
 * accepts as a base_tree / parent afterwards.
 */
export async function seedRepository(
  token: string,
  owner: string,
  repo: string,
  branch: string
): Promise<string> {
  const content = [
    "# dependencies",
    "/node_modules",
    "/.pnp",
    ".pnp.js",
    "",
    "# next.js",
    "/.next/",
    "/out/",
    "",
    "# production",
    "/build",
    "",
    "# testing",
    "/coverage",
    "",
    "# misc",
    ".DS_Store",
    "*.pem",
    "npm-debug.log*",
    "",
    "# env",
    ".env",
    ".env.local",
    ".env.development.local",
    "",
    "# fleet sandbox",
    "/fleet-sandbox",
    "",
  ].join("\n");
  const { status, body } = await request(
    token,
    "PUT",
    `/repos/${owner}/${repo}/contents/.gitignore`,
    {
      message: "fleet: initialize repository",
      branch,
      content: Buffer.from(content, "utf-8").toString("base64"),
    }
  );
  const commitSha = (body as { commit?: { sha?: unknown } })?.commit?.sha;
  if (status !== 201 || typeof commitSha !== "string") {
    const message = (body as { message?: unknown })?.message;
    throw new GitHubError(
      `Could not initialize ${owner}/${repo} (${status})${typeof message === "string" ? ` — ${message}` : ""}.`,
      status,
      "GITHUB_UPLOAD_FAILED"
    );
  }
  return commitSha;
}

export async function createBlob(
  token: string,
  owner: string,
  repo: string,
  content: string
): Promise<string> {
  const { status, body } = await request(token, "POST", `/repos/${owner}/${repo}/git/blobs`, {
    content,
    encoding: "utf-8",
  });
  const sha = (body as { sha?: unknown })?.sha;
  if (status !== 201 || typeof sha !== "string") {
    const message = (body as { message?: unknown })?.message;
    throw new GitHubError(
      `Could not create blob (${status})${typeof message === "string" ? ` — ${message}` : ""}.`,
      status,
      "GITHUB_UPLOAD_FAILED"
    );
  }
  return sha;
}

export async function createTree(
  token: string,
  owner: string,
  repo: string,
  baseSha: string | null,
  entries: Array<{ path: string; sha: string }>
): Promise<string> {
  // GitHub accepts a commit sha as base_tree (it resolves to the commit's
  // tree), which keeps first-publish (seeded) and re-publish flows identical.
  const { status, body } = await request(token, "POST", `/repos/${owner}/${repo}/git/trees`, {
    base_tree: baseSha ?? undefined,
    tree: entries.map((entry) => ({
      path: entry.path,
      mode: "100644",
      type: "blob",
      sha: entry.sha,
    })),
  });
  const sha = (body as { sha?: unknown })?.sha;
  if (status !== 201 || typeof sha !== "string") {
    const message = (body as { message?: unknown })?.message;
    throw new GitHubError(
      `Could not create tree (${status})${typeof message === "string" ? ` — ${message}` : ""}.`,
      status,
      "GITHUB_UPLOAD_FAILED"
    );
  }
  return sha;
}

export async function createCommit(
  token: string,
  owner: string,
  repo: string,
  treeSha: string,
  parents: string[],
  message: string
): Promise<string> {
  const { status, body } = await request(token, "POST", `/repos/${owner}/${repo}/git/commits`, {
    message,
    tree: treeSha,
    parents,
  });
  const sha = (body as { sha?: unknown })?.sha;
  if (status !== 201 || typeof sha !== "string") {
    const message = (body as { message?: unknown })?.message;
    throw new GitHubError(
      `Could not create commit (${status})${typeof message === "string" ? ` — ${message}` : ""}.`,
      status,
      "GITHUB_PUSH_FAILED"
    );
  }
  return sha;
}

async function updateRef(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  sha: string
): Promise<void> {
  const { status } = await request(token, "PATCH", `/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
    sha,
    force: true,
  });
  if (status !== 200) {
    throw new GitHubError(
      `GitHub rejected the push to ${branch} (${status}).`,
      status,
      "GITHUB_PUSH_FAILED"
    );
  }
}

export async function createRef(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  sha: string
): Promise<void> {
  const { status } = await request(token, "POST", `/repos/${owner}/${repo}/git/refs`, {
    ref: `refs/heads/${branch}`,
    sha,
  });
  if (status !== 201) {
    throw new GitHubError(
      `Could not create branch ${branch} (${status}).`,
      status,
      "GITHUB_PUSH_FAILED"
    );
  }
}

/** Creates the branch if missing, otherwise fast-forwards it. */
export async function ensureRefOnBranch(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  sha: string
): Promise<void> {
  try {
    await updateRef(token, owner, repo, branch, sha);
  } catch {
    await createRef(token, owner, repo, branch, sha);
  }
}

export async function deleteRepository(token: string, owner: string, repo: string): Promise<void> {
  const { status } = await request(token, "DELETE", `/repos/${owner}/${repo}`);
  if (status !== 204 && status !== 404) {
    throw new GitHubError(`Could not delete ${owner}/${repo} (${status}).`, status);
  }
}