/**
 * Review handler — the worker half of "Review".
 *
 * Two post-build agents that work from the REAL generated files on disk:
 *  - GENERATE_README writes a genuine README.md describing what was actually
 *    generated (real file tree, real detected dependencies, real component and
 *    page names).
 *  - AGENT_REVIEW scans the real files for actual findings (TODO/FIXME/placeholder
 *    markers, empty files, broken placeholder exports) plus failure context from
 *    the real build runs, and persists them as a report.
 *
 * Nothing here invents content: every line is derived from files that were
 * actually generated for this project.
 */

import prisma from "@/lib/prisma";
import type { Prisma } from "@prisma/client";
import { loadGeneratedFiles, type GeneratedFileRecord } from "../context";
import { writeWorkspaceFile } from "../workspace";
import type { ClaimedRun } from "../queue";
import { HandlerError, type RunOutcome } from "./shared";

const MAX_README_FILES = 120;
const MAX_SNIPPET_LENGTH = 120;

function countLines(content: string, predicate: RegExp): number {
  let count = 0;
  for (const line of content.split(/\r?\n/)) {
    if (predicate.test(line)) count += 1;
  }
  return count;
}

/** Picks real dependency names out of an actual generated package.json. */
function detectedDependencies(files: GeneratedFileRecord[]): string[] {
  const pkg = files.find((f) => f.filePath.endsWith("package.json"));
  if (!pkg) return [];
  const parsed = (() => {
    try {
      return JSON.parse(pkg.content) as {
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
        scripts?: Record<string, string>;
      };
    } catch {
      return null;
    }
  })();
  if (!parsed) return [];
  const names = [
    ...Object.keys(parsed.dependencies ?? {}),
    ...Object.keys(parsed.devDependencies ?? {}),
  ].sort();
  return names;
}

function realComponentAndPageNames(files: GeneratedFileRecord[]): {
  components: string[];
  pages: string[];
} {
  const components = new Set<string>();
  const pages = new Set<string>();
  for (const file of files) {
    const path = file.filePath;
    if (path.startsWith("src/components/") && path.endsWith(".tsx")) {
      const match = path.split("/").pop()?.replace(/\.tsx$/, "");
      if (match) components.add(match);
    } else if (/src\/(pages|app)\/.*\.(tsx|ts)/.test(path)) {
      const match = path
        .replace(/^src\/(pages|app)\//, "")
        .replace(/\/page\.(tsx|ts)$/, "")
        .replace(/(\.tsx|\.ts)$/, "")
        .replace(/^index$/, "/")
        .replace(/^$/, "/");
      pages.add(match.startsWith("/") ? match : `/${match}`);
    }
  }
  const order = (set: Set<string>) => Array.from(set).sort();
  return { components: order(components), pages: order(pages) };
}

async function writeArtifact(
  run: ClaimedRun,
  type: string,
  filePath: string,
  content: string,
  metadata: Record<string, unknown>
): Promise<{ id: string; ref: string; checksum: string }> {
  const written = await writeWorkspaceFile(run.projectId, filePath, content);
  const artifact = await prisma.projectArtifact.create({
    data: {
      projectId: run.projectId,
      type,
      version: 1,
      filePath,
      contentRef: written.ref,
      checksum: written.checksum,
      createdBy: run.userId,
      metadataJson: metadata as unknown as Prisma.InputJsonValue,
    },
  });
  return { id: artifact.id, ref: written.ref, checksum: written.checksum };
}

const DETERMINISTIC_PROVIDER: NonNullable<RunOutcome["provider"]> = {
  name: "fleet",
  model: "deterministic",
  external: false,
};

export async function handleReviewTask(run: ClaimedRun): Promise<RunOutcome> {
  const project = await prisma.project.findUnique({
    where: { id: run.projectId },
    select: { name: true },
  });
  if (!project) throw new HandlerError("PROJECT_NOT_FOUND", "The project no longer exists.");

  const files = await loadGeneratedFiles(run.projectId);
  if (files.length === 0) {
    throw new HandlerError(
      "NO_GENERATED_FILES",
      "Review agents need generated files. Run the build first."
    );
  }

  if (run.taskType === "GENERATE_README") {
    return generateReadme(run, project.name, files);
  }
  if (run.taskType === "AGENT_REVIEW") {
    return runReview(run, project.name, files);
  }

  throw new HandlerError("UNSUPPORTED_TASK", `No review handler for "${run.taskType}".`);
}

async function generateReadme(
  run: ClaimedRun,
  projectName: string,
  files: GeneratedFileRecord[]
): Promise<RunOutcome> {
  const deps = detectedDependencies(files);
  const { components, pages } = realComponentAndPageNames(files);

  const sections: string[] = [
    `# ${projectName}`,
    "",
    `> Generated by Fleet's Business Builder. This README describes the files that were actually generated for this project.`,
    "",
    "## What was generated",
    `- **Files:** ${files.length} generated file${files.length === 1 ? "" : "s"}`,
    `- **Components:** ${components.length} real component${components.length === 1 ? "" : "s"}`,
    `- **Pages/routes:** ${pages.length} real page route${pages.length === 1 ? "" : "s"}`,
    "",
  ];

  if (deps.length > 0) {
    sections.push("## Detected dependencies", "", "Detected from the real `package.json`:", "");
    for (const name of deps) sections.push(`- \`${name}\``);
    sections.push("");
  } else {
    sections.push("## Dependencies", "", "_No `package.json` was generated for this project._", "");
  }

  sections.push("## Project layout", "", "Real generated file paths:");
  const displayed = files.slice(0, MAX_README_FILES);
  for (const file of displayed) {
    sections.push(`- \`${file.filePath}\``);
  }
  if (files.length > MAX_README_FILES) {
    sections.push(`- _… and ${files.length - MAX_README_FILES} more files_`);
  }
  sections.push("");

  if (components.length > 0) {
    sections.push("## Components", "");
    for (const name of components) sections.push(`- \`${name}\``);
    sections.push("");
  }
  if (pages.length > 0) {
    sections.push("## Pages / routes", "");
    for (const page of pages) sections.push(`- \`${page}\``);
    sections.push("");
  }

  sections.push(
    "## Stack",
    "",
    deps.length > 0
      ? "- Determined from the generated `package.json` dependencies."
      : "- No dependency manifest was generated. Dependency installation is a sandbox step this environment cannot run honestly.",
    "",
    "## Plumbing & lifecycle",
    "- This README (and the review report) are regenerated by the Review stage agents from the real files on disk.",
    ""
  );

  const readme = sections.join("\n");
  const artifact = await writeArtifact(run, "README", "README.md", readme, {
    kind: "generated-docs",
    files: files.length,
    components: components.length,
    pages: pages.length,
    dependencies: deps,
  });

  return {
    provider: DETERMINISTIC_PROVIDER,
    outputArtifactIds: [artifact.id],
    message: `README written for ${files.length} real file${files.length === 1 ? "" : "s"}.`,
  };
}

interface Finding {
  severity: "info" | "warning" | "error";
  filePath: string;
  detail: string;
  line?: number;
}

async function runReview(
  run: ClaimedRun,
  projectName: string,
  files: GeneratedFileRecord[]
): Promise<RunOutcome> {
  const findings: Finding[] = [];

  const markerPattern = /(TODO|FIXME|XXX|HACK)\b/g;
  for (const file of files) {
    const lines = file.content.split(/\r?\n/);
    lines.forEach((line, index) => {
      const match = line.match(markerPattern);
      if (match) {
        findings.push({
          severity: "warning",
          filePath: file.filePath,
          line: index + 1,
          detail: `Contains marker "${match[0]}" — ${line.trim().slice(0, MAX_SNIPPET_LENGTH)}`,
        });
      }
    });
  }

  const empty = files.filter((f) => f.content.trim().length === 0);
  for (const file of empty) {
    findings.push({
      severity: "warning",
      filePath: file.filePath,
      detail: "Generated file is empty.",
    });
  }

  const placeholder = new Set([
    "placeholder",
    "coming soon",
    "to be implemented",
    "not implemented",
    "example text",
    "lorem ipsum",
  ]);
  for (const file of files) {
    const lower = file.content.toLowerCase();
    const hits = Array.from(placeholder).filter((p) => lower.includes(p));
    if (hits.length > 0) {
      findings.push({
        severity: "info",
        filePath: file.filePath,
        detail: `Contains placeholder content ("${hits.join(", ")}").`,
      });
    }
  }

  const pkg = files.find((f) => f.filePath.endsWith("package.json"));
  if (!pkg) {
    findings.push({
      severity: "error",
      filePath: "package.json",
      detail: "No package.json was generated, so dependency install is not possible.",
    });
  }

  // Failure context from the real build runs — never invented.
  const failedBuilds = await prisma.agentRun.findMany({
    where: {
      projectId: run.projectId,
      taskType: { in: ["INSTALL_DEPENDENCIES", "RUN_LINT", "RUN_TYPECHECK"] },
      status: { in: ["FAILED", "ERROR"] },
    },
    orderBy: { createdAt: "desc" },
    take: 3,
    select: { taskType: true, errorMessage: true },
  });
  for (const build of failedBuilds) {
    findings.push({
      severity: "error",
      filePath: build.taskType.toLowerCase(),
      detail: build.errorMessage ?? `${build.taskType} failed without a recorded message`,
    });
  }

  const ascii = new Set<string>();
  for (const file of files) {
    if (/[^\x00-\x7F]/.test(file.content)) ascii.add(file.filePath);
  }
  if (ascii.size > 0) {
    findings.push({
      severity: "info",
      filePath: Array.from(ascii).slice(0, 5).join(", ") + (ascii.size > 5 ? ", …" : ""),
      detail: "Non-ASCII characters present in generated content.",
    });
  }

  const readmeExists = files.some((f) => f.filePath === "README.md" || f.type === "README");
  if (!readmeExists) {
    findings.push({
      severity: "warning",
      filePath: "README.md",
      detail: "No README found for the project.",
    });
  }

  const bySeverity = (s: Finding["severity"]) => findings.filter((f) => f.severity === s).length;

  const report = [
    `# Agent review — ${projectName}`,
    `Reviewed ${files.length} real generated files, found ${findings.length} finding(s).`,
    `Severity: ${bySeverity("error")} error, ${bySeverity("warning")} warning, ${bySeverity("info")} info.`,
    "",
    ...findings.map(
      (f) => `- [${f.severity.toUpperCase()}]${f.filePath}${f.line ? `:${f.line}` : ""} — ${f.detail}`
    ),
    "",
  ].join("\n");

  const artifact = await writeArtifact(run, "REVIEW_REPORT", "reports/review-report.log", report, {
    kind: "agent-review",
    files: files.length,
    findings: findings.length,
    bySeverity: { error: bySeverity("error"), warning: bySeverity("warning"), info: bySeverity("info") },
  });

  return {
    provider: DETERMINISTIC_PROVIDER,
    outputArtifactIds: [artifact.id],
    message: `Found ${findings.length} real finding${findings.length === 1 ? "" : "s"}.`,
  };
}